films = [
{ 
    id:1,
    name: "Matrix",
    director: " Lana Wachowski, Lilly Wachowski",
    year: 1999,
    rating: 8.7,
    genre: "action",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcgBJGoclqi7UrGpMr3meUb_OeZd8XovrTL2HLUSds7g&s",
},
{ 
    id:2,
    name: "The Lord of the Rings: The Fellowship of the Ring",
    director: "Peter Jackson",
    year: 2001,
    rating: 8.9,
    genre: "action",
    image:"https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg",
},
{ 
    id:3,
    name: "The Shawshank Redemption",
    director: "Frank Darabont",
    year: 1994,
    rating: 9.3,
    genre: "drama",
    image:"https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
},
{ 
    id:4,
    name: "The Godfather",
    director: "Francis Ford Coppola",
    year: 1972,
    rating: 9.2,
    genre: "Crime",
    image:"https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
},
{ 
    id:5,
    name: "The Dark Knight",
    director: "Christopher Nolan",
    year: 2008,
    rating: 9.0,
    genre: "action",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROE5xwAH1C5P47qMAyG2rffn9KF4JjWks7sbBXPy1TJw&s",
},
{ 
    id:6,
    name: "Forrest Gump",
    director: "Robert Zemenckis",
    year: 1994,
    rating: 8.8,
    genre: "romance",
    image:"https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg",
},
{ 
    id:7,
    name: "Fight Club",
    director: "David Fincher",
    year: 1999,
    rating: 8.8,
    genre: "drama",
    image:"https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
},
{ 
    id:8,
    name: "Goodfellas",
    director: "Martin Scorsese",
    year: 1990,
    rating: 8.7,
    genre: "biography",
    image:"https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
},
];

